Feature add profile
nerubia/grobrix pull request #12
Opened 2024-01-15 00:54 UTC by jatnerubia

2024-01-17 05:59 UTC, Dev-Nino approved these changes

2024-01-17 06:34 UTC, g-six requested changes

2024-01-17 06:34 UTC, g-six commented on src/app/add-profile/components/header.tsx
> +            <span></span>
What is this empth span for @jatnerubia ?

2024-01-17 06:34 UTC, g-six commented on src/app/add-profile/components/template-form.tsx
> +                    <label htmlFor="#" className="text-secondary-200 text-sm">
`htmlFor="#"` looks like an unintentional mistake?

2024-01-17 06:34 UTC, g-six commented on src/app/add-profile/components/template-light-form.tsx
> +                                                htmlFor=""
remove this if not needed as blank value serves no purpose `htmlFor=""`

2024-01-17 06:34 UTC, g-six commented on src/app/add-profile/components/template-light-form.tsx
> +                                                htmlFor=""
remove this if not needed as blank value serves no purpose `htmlFor=""`

2024-01-17 06:34 UTC, g-six commented on src/app/add-profile/components/template-light-form.tsx
> +                                    <div className="flex gap-1 bg-secondary-25 text-[10px] px-2 py-[6px] rounded-full">
Please use propert tailwindcss sizes here.
`py-1.5` instead of py-[6px]

2024-01-17 06:56 UTC, jatnerubia commented on src/app/add-profile/components/header.tsx
> +            <span></span>
need to center the `add profile`

2024-01-17 06:57 UTC, jatnerubia commented
@g-six done ^^

2024-01-18 06:02 UTC, g-six approved these changes

2024-01-18 06:02 UTC, merged