add device templates page
nerubia/grobrix pull request #16
Opened 2024-01-15 08:46 UTC by jatnerubia

2024-01-16 06:37 UTC, Dev-Nino approved these changes

2024-01-17 06:35 UTC, g-six requested changes
Please review all the styling classes and resubmit for PR

2024-01-18 06:26 UTC, jatnerubia commented
@g-six done ^^

2024-01-18 06:27 UTC, g-six approved these changes

2024-01-18 06:27 UTC, merged