App context
nerubia/grobrix pull request #29
Opened 2024-01-17 03:54 UTC by jatnerubia

2024-01-17 04:54 UTC, Dev-Nino approved these changes

2024-01-17 06:39 UTC, g-six requested changes
Please take a look at tailwind.config.js to available branding colours instead of hardcoding the hex values.

2024-01-17 06:39 UTC, g-six commented on src/components/ui/device-card.tsx
>                  <p className="text-[#8E8F8E] text-sm font-light">Power Off</p>
Please take a look at tailwind.config.js to available branding colours instead of hardcoding the hex values.

2024-01-18 06:09 UTC, g-six approved these changes

2024-01-18 06:29 UTC, jatnerubia commented
@g-six done ^^

2024-01-18 06:32 UTC, g-six approved these changes

2024-01-18 06:32 UTC, merged