homepage revision
nerubia/grobrix pull request #30
Opened 2024-01-17 05:44 UTC by jatnerubia

2024-01-17 05:57 UTC, Dev-Nino approved these changes

2024-01-17 06:42 UTC, g-six requested changes

2024-01-17 06:42 UTC, g-six commented on src/app/page.tsx
>                              <span className="text-[#D35252]">Attention</span>
`"text-[#D35252]"` should be `text-desctructive-500`

2024-01-18 06:30 UTC, jatnerubia commented
@g-six done ^^

2024-01-18 06:32 UTC, g-six approved these changes

2024-01-18 06:32 UTC, merged